### ISSUE TITLE
Cannot open database file

### ISSUE THREAD

**Issue by mxenoph** [jdidion/papers2#1]
Hi,

I am trying to use the python API to access my Papers2 library on MAC (OS X Yosemite) and I have encountered an error. From what I gather the error comes from `sqlalchemy` and the fact that it can't open the database file.

``` python
File "/Library/Python/2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

The Papers2 library on my system is not under `~/Papers2` so I have also tried accessing the database with `db = Papers2(folder="/Users/mxenoph/Library/Application\ Support/Papers2")` but the error persists. All users have read permission for all files under the Papers2 directory so I am wondering where this error comes from. 

I would appreciate it if you would be able to help. I am trying to export the entire Papers2 library to BibTex so I can use it with LaTex. I know I could manually export it but it'd be best to get an updated version of the library every time I compile my document.

**Comment by jdidion** [comment]
I suspect that the problem is the backslash in the path. Try Papers2(folder="/Users/mxenoph/Library/Application Support/Papers2"). This will look for the database at /Users/mxenoph/Library/Application Support/Papers2/Library.papers2/Database.papersdb. Please confirm that that file exists.

**Comment by jdidion** [comment]
Additionally, BibTex output is not currently supported (only Zotero). If you implement BibTex export, please consider donating it to the project so others can benefit (using a pull request). Are you sure that the normal Papers2 BibTex export won't work for you?

**Comment by mxenoph** [comment]
Thank you, I hadn't noticed the backslash. The reason I want to programmatically export the library to bibtex is that while writing my thesis I will be adding papers to my library. While working on the draft I want to see the publications apart from the cite keys (better for figuring out what paper I'm talking about) so I would either have to export the library very often or just export it once when I'm done. I'm compiling the thesis in a Makefile so I just thought this would be a good idea.
